version: '3'
services:
  json-server:
    image: node:20.11.1
    volumes:
      - ./db.json:/app/db.json
    working_dir: /app
    command: json-server --port=5000 --watch db.json
    ports:
      - "5000:5000"
  angular-app:
    build: .
    ports:
      - "4200:4200"