# Usa la imagen oficial de node
FROM node:20.11.1 AS build

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo db.json para que json-server lo pueda usar
COPY db.json /app/db.json

# Instalar json-server globalmente
RUN npm install -g json-server

# Comando para ejecutar json-server
CMD ["json-server", "--port", "5000", "--watch","--host" ,"0.0.0.0","db.json"]
